version: '3'

services:
#  api:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    container_name: api
#    tty: true
#    image: app/api
#    ports:
#      - '8081:8080'
#    environment:
#      - PROFILE=dev
#      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#    links:
#      - db

#  db:
#    image: postgres:12-alpine
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_PASSWORD=123
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=subirapi

  rabbit:
    image: "rabbitmq:3-management"
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBIT_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"