name: Build & Tests - PR

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build & test with Maven
      run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir commons/prod && cp commons/target/commons-0.0.1-SNAPSHOT.jar commons/prod
      - run: mkdir consumer-microservice/prod && cp consumer-microservice/target/consumer-microservice-0.0.1-SNAPSHOT.jar consumer-microservice/prod
      - run: mkdir email-api/prod && cp email-api/target/email-api-0.0.1-SNAPSHOT.jar email-api/prod
      - run: mkdir subs-api/prod && cp subs-api/target/subs-api-0.0.1-SNAPSHOT.jar subs-api/prod
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: prod
